import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { OTPProvider } from "../components/context/OtpContext";
import { UserNameProvider } from "../components/context/UserNameContext";
import { NewPasswordProvider } from "../components/context/NewPasswordContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <UserNameProvider>
          <OTPProvider>
            <NewPasswordProvider>{children}</NewPasswordProvider>
            <ToastContainer></ToastContainer>
          </OTPProvider>
        </UserNameProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
